"""Generate standalone runtime packages shipped next to protected scripts."""

from __future__ import annotations

import base64
import hashlib
import os
import pathlib

from ..protection.keys import encode_key

_RUNTIME_ID_LEN = 6


def make_runtime_id(seed: str | None) -> str:
    if seed is None:
        return os.urandom(3).hex()
    return hashlib.sha256(f"openprotect-runtime:{seed}".encode()).hexdigest()[:_RUNTIME_ID_LEN]


def _prologue(outer_key: bytes, license_key: dict | None) -> str:
    lines = [
        "# generated by openprotect; do not edit",
        "import base64",
        f"_OUTER_KEY = base64.b64decode({encode_key(outer_key)!r})",
    ]
    if license_key:
        n_bytes = license_key["n"].to_bytes((license_key["n"].bit_length() + 7) // 8, "big")
        lines.append(
            f"_LICENSE_PUBLIC_N = int.from_bytes(base64.b64decode({base64.b64encode(n_bytes)!r}), 'big')"
        )
        lines.append(f"_LICENSE_PUBLIC_E = {license_key['e']}")
    return "\n".join(lines) + "\n"


def generate_runtime_package(
    dist_dir: pathlib.Path,
    runtime_id: str,
    outer_key: bytes,
    license_key: dict | None = None,
) -> pathlib.Path:
    pkg_dir = dist_dir / f"openprotect_runtime_{runtime_id}"
    pkg_dir.mkdir(parents=True, exist_ok=True)

    raw_loader = (
        pathlib.Path(__file__).parent / "standalone_loader.py"
    ).read_text(encoding="utf-8")
    # The embedded module gets a prologue before the loader body, so the
    # future-import must go (safe: openprotect targets 3.10+ where the
    # loader's annotations evaluate natively).
    loader_source = "\n".join(
        line
        for line in raw_loader.splitlines()
        if line.strip() != "from __future__ import annotations"
    )

    init_src = (
        "# generated by openprotect; do not edit\n"
        "from .openprotect_runtime import __pyarmor__, bcc_init\n"
    )
    runtime_src = _prologue(outer_key, license_key) + loader_source

    (pkg_dir / "__init__.py").write_text(init_src, encoding="utf-8")
    (pkg_dir / "openprotect_runtime.py").write_text(runtime_src, encoding="utf-8")
    return pkg_dir
